# Dawson Botsford zshrc https://github.com/dawsonbotsford/dotfiles
# Use this to lazy load bigger deps (like nvm)

lazy_source () {
  eval "$1 () { [ -f $2 ] && source $2 && $1 \$@ }"
}

# NVM_SOURCE=$HOME/.nvm/nvm.sh
# lazy_source nvm $NVM_SOURCE

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" --no-use # This loads nvm

# Increase history size
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000

# eval "$(rbenv init - --no-rehash)"

# Extend path
export PATH="$PATH:$HOME/cli"
# export PATH=/usr/local/bin:$PATH
# export PATH="$PATH:$HOME/.rvm/bin"

export LANG=en_US.UTF-8
export EDITOR='vim'

eval "$(fasd --init auto)"

# backwards search
# bindkey "^R" history-incremental-search-backward

# Yank directly to clipboard OSX
set clipboard=unnamed

########## ALIASES ###########
alias sz='source ~/.zshrc'
alias vz='$EDITOR ~/.zshrc'
alias vv='$EDITOR ~/.vimrc'

#daemon watching
alias na="nodemon --exec 'ava'"
alias nx="nodemon --exec 'xo'"
alias nt="nodemon --exec 'npm test'"
alias pydemon="nodemon --exec 'python' "

#youtube-dl mp3 alias
alias youtube-dl-mp3="youtube-dl --extract-audio --audio-format mp3 "

# Shortcuts to executable files
alias subl="/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl"
# alias chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"

# oh my zsh
export ZSH=/Users/dawsonbotsford/.oh-my-zsh
ZSH_THEME="agnoster"
plugins=(git)
source $ZSH/oh-my-zsh.sh

ZSHRCS_HOME="$HOME/Dropbox/dotfiles/zshrcs"
source "$ZSHRCS_HOME/arcAliases.sh"
source "$ZSHRCS_HOME/gitAliases.sh"
source "$ZSHRCS_HOME/npmAliases.sh"
source "$ZSHRCS_HOME/utilities.sh"
source "$ZSHRCS_HOME/bindkey.sh"

UBER_PRIVATE_RC="$HOME/uberPrivaterc"
if [ -f $UBER_PRIVATE_RC ]
then
  # source $UBER_PRIVATE_RC
fi

# KEEP AT END OF FILE
#Removes username from prompt status line
prompt_context(){}

# added by travis gem
# [ -f /Users/dawsonbotsford/.travis/travis.sh ] && source /Users/dawsonbotsford/.travis/travis.sh
