
DROPBOX_PATH=$HOME/dropbox

# Load z https://github.com/rupa/z
. $DROPBOX_PATH/dotfiles/scripts/z.sh

# Use this to lazy load bigger deps (like nvm)
# lazy_source () {
#   eval "$1 () { [ -f $2 ] && source $2 && $1 \$@ }"
# }
nits () {
  npm install --save $1 && npm install --save-dev @types/$1
}

# Source all other zshrc helpers/aliases
source "$DROPBOX_PATH/dotfiles/sh-helpers.sh"

# Increase history size
export HISTFILE=~/.zsh_history
export HISTSIZE=100000000
export SAVEHIST=100000000

# ruby
eval "$(rbenv init - --no-rehash)"

# Extend path
export PATH="$PATH:$HOME/cli"
export PATH="$PATH:$HOME/.config/yarn/global/node_modules/.bin"

export PATH="/usr/local/sbin:$PATH"

# export PATH="$PATH:$(yarn global bin)"
# export PATH="$HOME/.yarn/bin:$PATH"
# yarn config set prefix $(npm config get prefix)

export LANG=en_US.UTF-8

# Yank directly to clipboard OSX
clipboard=unnamed

########## Aliases ###########
export EDITOR=nvim # Neovim is bae
export VISUAL="$EDITOR"
export GIT_EDITOR="$EDITOR"

alias e="echo"
alias d="docker"
alias dc="docker-compose"
alias python="python3"
alias v="$EDITOR"
alias vim="$EDITOR"
alias vz="$EDITOR ~/.zshrc"
alias vv="$EDITOR $HOME/.config/nvim/init.vim"
alias vh="$EDITOR ~/.zsh_history"
alias sz="source ~/.zshrc"

# daemon watching
alias na="nodemon --exec 'ava'"
alias nx="nodemon --exec 'xo'"
alias nt="nodemon --exec 'npm test'"

# youtube-dl mp3 alias
alias youtube-dl-mp3="youtube-dl --extract-audio --audio-format mp3 "

# oh my zsh
export ZSH=$HOME/.oh-my-zsh

POWERLEVEL9K_MODE='nerdfont-complete'
export ZSH_THEME="powerlevel9k/powerlevel9k"
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator)

# plugins=(git)
plugins+=(zsh-autosuggestions) # Predictive suggestions
plugins+=(pipenv)
plugins+=(yarn)

source $ZSH/oh-my-zsh.sh
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=3' # Suggest in orange

# vim fuzzy file searching with ripgrep
# https://medium.com/@crashybang/supercharge-vim-with-fzf-and-ripgrep-d4661fc853d2
# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
# export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'

###################### KEEP AT END OF FILE ####################

# https://github.com/dawsbot/pluc
source $(pluc-cli --destinationPath)
function pluc() {
  pluc-cli "$@"
  source "$(pluc-cli --destinationPath)"
}

#Removes username from prompt status line
prompt_context(){}

# added by travis gem
# [ -f /Users/dawsonbotsford/.travis/travis.sh ] && source /Users/dawsonbotsford/.travis/travis.sh

# added by fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# The next line updates PATH for the Google Cloud SDK.
# if [ -f '/Users/dawsonbotsford/Downloads/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/dawsonbotsford/Downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
# if [ -f '/Users/dawsonbotsford/Downloads/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/dawsonbotsford/Downloads/google-cloud-sdk/completion.zsh.inc'; fi

# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
# export PATH="$PATH:$HOME/.rvm/bin"

alias play="cd "$(mktemp -d)""
alias gre="git pull --rebase origin master"
alias getGlobalGitignore="git config --get core.excludesfile"
alias gam="ga -A && gc -m "
alias nv="node -v"
alias ncc="npm cache clean"
alias l="ls"
alias dun="terminal-notifier -message 'done!'"
alias yarnt="yarn && t"
alias nif="npm init -f"
alias gm="git merge"
alias gms="git merge --squash"
alias npmv="npm -v"
alias y="yarn"
alias yl="yarn link"
alias ya="yarn add"
alias yr="yarn remove"
alias yt="yarn && yarn test"
alias yad="yarn add --dev"
alias vp="vim $(pluc-cli --sourcePath) && pluc --transpile"
alias vpp="vim $(pluc-cli --destinationPath)"
alias yga="yarn global add"
alias cnt="cn && t"
alias ys="yarn start"
alias yi="yarn init"
alias yiy="yarn init -y"
alias nin="npm info"
alias vd="vim diff"
alias bomb="cd .. && rm -rf $OLDPWD"
alias bi="brew install"
alias gb="git branch"
alias rn="rm -rf node_modules"
alias rny="rn && y"
alias nrd="npm run dev"
alias ygr="yarn global remove"
alias ns="npm start"
alias nu="npm update"
alias pr="hub pull-request"
alias gr="git remote"
alias ag="ag --ignore node_modules "
alias dy="rm -rf node_modules && y"
alias dyt="dy && t"
alias gfo="git fetch origin"
alias c="hicat"
alias v="vim"
alias yst="yarn storybook"
alias up="gch master && gpu"
alias yf="yarn flow"
alias yb="yarn build"
alias gd="git diff"
alias gp="git push"
alias ga="git add"
alias gs="git status"
alias gl="git log --graph --oneline --decorate"
alias gi="git init"
alias gch="git checkout"
alias gchb="git checkout -b"
alias gc="git commit"
alias gmm="git merge master"
alias yj="yarn jest"
alias ye="yarn e2e"
alias ytsc="yarn tsc"
alias yw="yarn watch"
alias di="docker images"
alias dc="docker-compose"
alias dcu="docker-compose up"
alias gchm="git checkout master && git pull origin master"
alias gchd="git checkout develop && git pull origin develop"
alias gcp="git cherry-pick"
alias yscn="yarn start:cn"
alias gsta="git stash apply"
alias gst="git stash"
alias grc="git rebase --continue"
alias gra="git rebase --abort"
alias ysd="yarn start:dev"
alias yd="yarn dev"
alias p="python"
alias pa="python server/app.py"

mylast () {
        re='^[0-9]+$'
        if ! [[ $1 =~ $re ]] ; then
           echo "error: $1 not a number" >&2
        else
           history | awk '{a[$2]++} END {for (i in a) print a[i], i}' | sort -rn | head -n $1
        fi
      }
