# github.com/dawsbot/dotfiles

DROPBOX_PATH=$HOME/dropbox

# Load z https://github.com/rupa/z
. $DROPBOX_PATH/dotfiles/scripts/z.sh

# Use this to lazy load bigger deps (like nvm)
# lazy_source () {
#   eval "$1 () { [ -f $2 ] && source $2 && $1 \$@ }"
# }

# NVM_SOURCE=$HOME/.nvm/nvm.sh
# lazy_source nvm $NVM_SOURCE

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

# Increase history size
export HISTFILE=~/.zsh_history
export HISTSIZE=100000
export SAVEHIST=100000

eval "$(rbenv init - --no-rehash)"

# Go
export GOPATH=$HOME/golang
export PATH="$PATH:$GOPATH/bin"

# Extend path
export PATH="$PATH:$HOME/cli"
# export PATH=$HOME/.nvm/versions/node/v6.9.4/bin:$PATH
export PATH="$PATH:$(yarn global bin)"
export PATH="$HOME/.yarn/bin:$PATH"

export LANG=en_US.UTF-8

# Yank directly to clipboard OSX
clipboard=unnamed

########## Aliases ###########
export EDITOR=nvim # Neovim is bae
export VISUAL="$EDITOR"
export GIT_EDITOR="$EDITOR"

alias v="$EDITOR"
alias vim="$EDITOR"
alias vz="$EDITOR ~/.zshrc"
alias vv="$EDITOR ~/.vimrc"
alias vh="$EDITOR ~/.zsh_history"
alias sz="source ~/.zshrc"

# daemon watching
alias na="nodemon --exec 'ava'"
alias nx="nodemon --exec 'xo'"
alias nt="nodemon --exec 'npm test'"
alias pydemon="nodemon --exec 'python' "

# youtube-dl mp3 alias
alias youtube-dl-mp3="youtube-dl --extract-audio --audio-format mp3 "

# oh my zsh
export ZSH=$HOME/.oh-my-zsh
export ZSH_THEME="agnoster"
plugins=(git)
plugins=(zsh-autosuggestions) # Predictive suggestions
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=3' # Suggest in orange

source $ZSH/oh-my-zsh.sh

ZSHRCS_HOME="$DROPBOX_PATH/dotfiles/zshrcs"
source "$ZSHRCS_HOME/gitAliases.sh"
source "$ZSHRCS_HOME/npmAliases.sh"
source "$ZSHRCS_HOME/utilities.sh"

# vim fuzzy file searching with ripgrep
# https://medium.com/@crashybang/supercharge-vim-with-fzf-and-ripgrep-d4661fc853d2
# --files: List files that would be searched but do not search
# --no-ignore: Do not respect .gitignore, etc...
# --hidden: Search hidden files and folders
# --follow: Follow symlinks
# --glob: Additional conditions for search (in this case ignore everything in the .git/ folder)
export FZF_DEFAULT_COMMAND='rg --files --no-ignore --hidden --follow --glob "!.git/*"'

# Source extra uber rc file if exists (won't on personal machine)
UBER_PRIVATE_RC="$HOME/uberPrivaterc.sh"
[ -f $UBER_PRIVATE_RC ] && source $UBER_PRIVATE_RC

###################### KEEP AT END OF FILE ####################

# https://github.com/dawsbot/pluc
source $(pluc-cli --destinationPath)
function pluc() {
  pluc-cli "$@"
  source "$(pluc-cli --destinationPath)"
}

#Removes username from prompt status line
prompt_context(){}

# added by travis gem
[ -f /Users/dawsonbotsford/.travis/travis.sh ] && source /Users/dawsonbotsford/.travis/travis.sh

# added by fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
